const DATE_FORMAT_EDIT = 'DD/MM/YY HH:mm';
const DATE_FORMAT_POINT_DAY = 'MMM DD';
const DATE_FORMAT_DAY_RESULTS = 'DD MMM';
const DATE_FORMAT_POINT_HOURS = 'HH:mm';

export {DATE_FORMAT_DAY_RESULTS, DATE_FORMAT_EDIT, DATE_FORMAT_POINT_DAY, DATE_FORMAT_POINT_HOURS};
